service: aws-selenium-headless-chronium-example

package:
  individually: true

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  snsTopic: "snsTopicTrigger"
  holdingBucket: "selenium-data-extractor-tester"

provider:
  name: aws
  runtime: python3.6
  memorySize: 3008 # optional, in MB, default is 1024. 128-3008MB range
  timeout: 900
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage,'dev'}
  apiKeys: 
    - ${opt:key, 'api_key'}
  iamRoleStatements:
    - Effect: "Allow"
      Resource: { "Fn::Join" : [":", ["arn:aws:sns:${self:custom.region}", { "Ref" : "AWS::AccountId" }, "${self:custom.snsTopic}" ] ]  }
      Action:
        - "sns:*"
  iamManagedPolicies:
    - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  mainEngine:
    environment:
      aws_region: ${file(../config/aws.json):aws_region}
      holding_bucket: ${self:custom.holdingBucket}
      login_username: ${file(../config/aws.json):username}
      login_password: ${file(../config/aws.json):password}
    handler: main.engine
    package:
      individually: True
      exclude:
        - publish.py
        - results.py
    layers: # Reference CloudFormation Outputs
      - ${cf:selenium-layer-${opt:stage, 'dev'}.SeleniumLayerExport}
      - ${cf:selenium-layer-${opt:stage, 'dev'}.ChromedriverLayerExport}
      - ${cf:txt-requirements-${opt:stage, 'dev'}.TxtReqLayerExport}
    timeout: 900 # optional, in seconds, default is 6
    memorySize: 3008 # optional, in MB, default is 1024. 128-3008MB range
    events:
      - sns: ${self:custom.snsTopic}

  snsLambdaPublisher:
    handler: publish.handler
    package:
      individually: true
      exclude:
        - func/**
        - main.py
        - results.py
    layers: # Reference CloudFormation Outputs
      - ${cf:txt-requirements-${opt:stage, 'dev'}.TxtReqLayerExport}
    environment:
      aws_region: ${file(../config/aws.json):aws_region}
      holding_bucket: ${self:custom.holdingBucket}
      login_username: ${file(../config/aws.json):username}
      login_password: ${file(../config/aws.json):password}
      sns_topic: ${self:custom.snsTopic}
      sns_topic_arn: { "Fn::Join" : [":", ["arn:aws:sns:${self:custom.region}", { "Ref" : "AWS::AccountId" }, "${self:custom.snsTopic}" ] ]  }
    events:
      - http:
          path: ${opt:publish, 'publish'}
          method: get
          cors: true
          private: true
          integration: lambda
          memorySize: 3008 # optional, in MB, default is 1024. 128-3008MB range
          request:
            template:
              application/json: >
                {
                  "arg" : "$input.params('arg')"
                }

  getResults:
    handler: results.handler
    iamRoleStatementsInherit: true
    iamManagedPolicies:
    - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
    package:
      individually: true
      exclude:
        - func/**
        - main.py
        - publish.py
    layers: # Reference CloudFormation Outputs
      - ${cf:txt-requirements-${opt:stage, 'dev'}.TxtReqLayerExport}
    environment:
      aws_region: ${file(../config/aws.json):aws_region}
      holding_bucket: ${self:custom.holdingBucket}
    events:
      - http:
          path: ${opt:result, 'results'}
          method: get
          cors: true
          private: true
          integration: lambda
          memorySize: 3008 # optional, in MB, default is 1024. 128-3008MB range
          request:
            template:
              application/json: >
                {
                  "arg" : "$input.params('arg')"
                }
                